/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const DemoRecord = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Nat,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
});
export const DemoRequest = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'company' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  '__demoRequests' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [IDL.Vec(DemoRecord)],
      ['query'],
    ),
  '__nextDemoId' : IDL.Func([], [IDL.Reserved], ['query']),
  'listDemoRequests' : IDL.Func([], [IDL.Vec(DemoRecord)], ['query']),
  'submitDemoRequest' : IDL.Func([DemoRequest], [DemoRecord], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const DemoRecord = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Nat,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
  });
  const DemoRequest = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'company' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    '__demoRequests' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [IDL.Vec(DemoRecord)],
        ['query'],
      ),
    '__nextDemoId' : IDL.Func([], [IDL.Reserved], ['query']),
    'listDemoRequests' : IDL.Func([], [IDL.Vec(DemoRecord)], ['query']),
    'submitDemoRequest' : IDL.Func([DemoRequest], [DemoRecord], []),
  });
};

export const init = ({ IDL }) => { return []; };